// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Kiseki.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kiseki.Arbiter.Proto {

  /// <summary>Holder for reflection information generated from Kiseki.proto</summary>
  public static partial class KisekiReflection {

    #region Descriptor
    /// <summary>File descriptor for Kiseki.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KisekiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxLaXNla2kucHJvdG8SBktpc2VraRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVz",
            "dGFtcC5wcm90byL7AgoGU2lnbmFsEikKBW5vbmNlGAEgASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcBINCgVqb2JJZBgCIAEoCRIkCglvcGVyYXRp",
            "b24YAyABKA4yES5LaXNla2kuT3BlcmF0aW9uEiYKB3ZlcnNpb24YBCABKA4y",
            "FS5LaXNla2kuQ2xpZW50VmVyc2lvbhIjCgVwbGFjZRgFIAMoCzIULktpc2Vr",
            "aS5TaWduYWwuUGxhY2USKwoJdGh1bWJuYWlsGAYgAygLMhguS2lzZWtpLlNp",
            "Z25hbC5UaHVtYm5haWwaRQoFUGxhY2USDwoHcGxhY2VJZBgBIAEoDRIOCgZz",
            "Y3JpcHQYAiABKAkSGwoTZXhwaXJhdGlvbkluU2Vjb25kcxgDIAEoDRpQCglU",
            "aHVtYm5haWwSHwoEdHlwZRgBIAEoDjIRLktpc2VraS5Bc3NldFR5cGUSDwoH",
            "YXNzZXRJZBgCIAEoDRIRCglhY2Nlc3NLZXkYAyABKAkiYAoIUmVzcG9uc2US",
            "JAoJb3BlcmF0aW9uGAEgASgOMhEuS2lzZWtpLk9wZXJhdGlvbhIPCgdzdWNj",
            "ZXNzGAIgASgIEg8KB21lc3NhZ2UYAyABKAkSDAoEZGF0YRgEIAEoCSpfCglP",
            "cGVyYXRpb24SDAoIT1BFTl9KT0IQABINCglDTE9TRV9KT0IQARISCg5FWEVD",
            "VVRFX1NDUklQVBACEhIKDkNMT1NFX0FMTF9KT0JTEAQSDQoJVEhVTUJOQUlM",
            "EAYqJgoNQ2xpZW50VmVyc2lvbhIICgROT05FEAASCwoGRUxFVkVOENsPKlkK",
            "CUFzc2V0VHlwZRIMCghDTE9USElORxAAEggKBEhFQUQQARIICgRNRVNIEAIS",
            "CQoFUExBQ0UQAxIICgRVU0VSEAQSDAoISEVBRFNIT1QQBRIHCgNYTUwQBkIj",
            "qgIUS2lzZWtpLkFyYml0ZXIuUHJvdG/KAglBcHBcUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Kiseki.Arbiter.Proto.Operation), typeof(global::Kiseki.Arbiter.Proto.ClientVersion), typeof(global::Kiseki.Arbiter.Proto.AssetType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kiseki.Arbiter.Proto.Signal), global::Kiseki.Arbiter.Proto.Signal.Parser, new[]{ "Nonce", "JobId", "Operation", "Version", "Place", "Thumbnail" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Kiseki.Arbiter.Proto.Signal.Types.Place), global::Kiseki.Arbiter.Proto.Signal.Types.Place.Parser, new[]{ "PlaceId", "Script", "ExpirationInSeconds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail), global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail.Parser, new[]{ "Type", "AssetId", "AccessKey" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kiseki.Arbiter.Proto.Response), global::Kiseki.Arbiter.Proto.Response.Parser, new[]{ "Operation", "Success", "Message", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Operation {
    [pbr::OriginalName("OPEN_JOB")] OpenJob = 0,
    [pbr::OriginalName("CLOSE_JOB")] CloseJob = 1,
    [pbr::OriginalName("EXECUTE_SCRIPT")] ExecuteScript = 2,
    [pbr::OriginalName("CLOSE_ALL_JOBS")] CloseAllJobs = 4,
    [pbr::OriginalName("THUMBNAIL")] Thumbnail = 6,
  }

  public enum ClientVersion {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("ELEVEN")] Eleven = 2011,
  }

  public enum AssetType {
    [pbr::OriginalName("CLOTHING")] Clothing = 0,
    [pbr::OriginalName("HEAD")] Head = 1,
    [pbr::OriginalName("MESH")] Mesh = 2,
    [pbr::OriginalName("PLACE")] Place = 3,
    [pbr::OriginalName("USER")] User = 4,
    [pbr::OriginalName("HEADSHOT")] Headshot = 5,
    [pbr::OriginalName("XML")] Xml = 6,
  }

  #endregion

  #region Messages
  public sealed partial class Signal : pb::IMessage<Signal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Signal> _parser = new pb::MessageParser<Signal>(() => new Signal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Signal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kiseki.Arbiter.Proto.KisekiReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Signal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Signal(Signal other) : this() {
      nonce_ = other.nonce_ != null ? other.nonce_.Clone() : null;
      jobId_ = other.jobId_;
      operation_ = other.operation_;
      version_ = other.version_;
      place_ = other.place_.Clone();
      thumbnail_ = other.thumbnail_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Signal Clone() {
      return new Signal(this);
    }

    /// <summary>Field number for the "nonce" field.</summary>
    public const int NonceFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp nonce_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Nonce {
      get { return nonce_; }
      set {
        nonce_ = value;
      }
    }

    /// <summary>Field number for the "jobId" field.</summary>
    public const int JobIdFieldNumber = 2;
    private string jobId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string JobId {
      get { return jobId_; }
      set {
        jobId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 3;
    private global::Kiseki.Arbiter.Proto.Operation operation_ = global::Kiseki.Arbiter.Proto.Operation.OpenJob;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kiseki.Arbiter.Proto.Operation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 4;
    private global::Kiseki.Arbiter.Proto.ClientVersion version_ = global::Kiseki.Arbiter.Proto.ClientVersion.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kiseki.Arbiter.Proto.ClientVersion Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "place" field.</summary>
    public const int PlaceFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Kiseki.Arbiter.Proto.Signal.Types.Place> _repeated_place_codec
        = pb::FieldCodec.ForMessage(42, global::Kiseki.Arbiter.Proto.Signal.Types.Place.Parser);
    private readonly pbc::RepeatedField<global::Kiseki.Arbiter.Proto.Signal.Types.Place> place_ = new pbc::RepeatedField<global::Kiseki.Arbiter.Proto.Signal.Types.Place>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Kiseki.Arbiter.Proto.Signal.Types.Place> Place {
      get { return place_; }
    }

    /// <summary>Field number for the "thumbnail" field.</summary>
    public const int ThumbnailFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail> _repeated_thumbnail_codec
        = pb::FieldCodec.ForMessage(50, global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail.Parser);
    private readonly pbc::RepeatedField<global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail> thumbnail_ = new pbc::RepeatedField<global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Kiseki.Arbiter.Proto.Signal.Types.Thumbnail> Thumbnail {
      get { return thumbnail_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Signal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Signal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Nonce, other.Nonce)) return false;
      if (JobId != other.JobId) return false;
      if (Operation != other.Operation) return false;
      if (Version != other.Version) return false;
      if(!place_.Equals(other.place_)) return false;
      if(!thumbnail_.Equals(other.thumbnail_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (nonce_ != null) hash ^= Nonce.GetHashCode();
      if (JobId.Length != 0) hash ^= JobId.GetHashCode();
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) hash ^= Operation.GetHashCode();
      if (Version != global::Kiseki.Arbiter.Proto.ClientVersion.None) hash ^= Version.GetHashCode();
      hash ^= place_.GetHashCode();
      hash ^= thumbnail_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (nonce_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Nonce);
      }
      if (JobId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(JobId);
      }
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Operation);
      }
      if (Version != global::Kiseki.Arbiter.Proto.ClientVersion.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Version);
      }
      place_.WriteTo(output, _repeated_place_codec);
      thumbnail_.WriteTo(output, _repeated_thumbnail_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (nonce_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Nonce);
      }
      if (JobId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(JobId);
      }
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Operation);
      }
      if (Version != global::Kiseki.Arbiter.Proto.ClientVersion.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Version);
      }
      place_.WriteTo(ref output, _repeated_place_codec);
      thumbnail_.WriteTo(ref output, _repeated_thumbnail_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (nonce_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Nonce);
      }
      if (JobId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JobId);
      }
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      if (Version != global::Kiseki.Arbiter.Proto.ClientVersion.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Version);
      }
      size += place_.CalculateSize(_repeated_place_codec);
      size += thumbnail_.CalculateSize(_repeated_thumbnail_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Signal other) {
      if (other == null) {
        return;
      }
      if (other.nonce_ != null) {
        if (nonce_ == null) {
          Nonce = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Nonce.MergeFrom(other.Nonce);
      }
      if (other.JobId.Length != 0) {
        JobId = other.JobId;
      }
      if (other.Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        Operation = other.Operation;
      }
      if (other.Version != global::Kiseki.Arbiter.Proto.ClientVersion.None) {
        Version = other.Version;
      }
      place_.Add(other.place_);
      thumbnail_.Add(other.thumbnail_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (nonce_ == null) {
              Nonce = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Nonce);
            break;
          }
          case 18: {
            JobId = input.ReadString();
            break;
          }
          case 24: {
            Operation = (global::Kiseki.Arbiter.Proto.Operation) input.ReadEnum();
            break;
          }
          case 32: {
            Version = (global::Kiseki.Arbiter.Proto.ClientVersion) input.ReadEnum();
            break;
          }
          case 42: {
            place_.AddEntriesFrom(input, _repeated_place_codec);
            break;
          }
          case 50: {
            thumbnail_.AddEntriesFrom(input, _repeated_thumbnail_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (nonce_ == null) {
              Nonce = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Nonce);
            break;
          }
          case 18: {
            JobId = input.ReadString();
            break;
          }
          case 24: {
            Operation = (global::Kiseki.Arbiter.Proto.Operation) input.ReadEnum();
            break;
          }
          case 32: {
            Version = (global::Kiseki.Arbiter.Proto.ClientVersion) input.ReadEnum();
            break;
          }
          case 42: {
            place_.AddEntriesFrom(ref input, _repeated_place_codec);
            break;
          }
          case 50: {
            thumbnail_.AddEntriesFrom(ref input, _repeated_thumbnail_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Signal message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Place : pb::IMessage<Place>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Place> _parser = new pb::MessageParser<Place>(() => new Place());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Place> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Kiseki.Arbiter.Proto.Signal.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Place() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Place(Place other) : this() {
          placeId_ = other.placeId_;
          script_ = other.script_;
          expirationInSeconds_ = other.expirationInSeconds_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Place Clone() {
          return new Place(this);
        }

        /// <summary>Field number for the "placeId" field.</summary>
        public const int PlaceIdFieldNumber = 1;
        private uint placeId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint PlaceId {
          get { return placeId_; }
          set {
            placeId_ = value;
          }
        }

        /// <summary>Field number for the "script" field.</summary>
        public const int ScriptFieldNumber = 2;
        private string script_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Script {
          get { return script_; }
          set {
            script_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "expirationInSeconds" field.</summary>
        public const int ExpirationInSecondsFieldNumber = 3;
        private uint expirationInSeconds_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ExpirationInSeconds {
          get { return expirationInSeconds_; }
          set {
            expirationInSeconds_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Place);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Place other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (PlaceId != other.PlaceId) return false;
          if (Script != other.Script) return false;
          if (ExpirationInSeconds != other.ExpirationInSeconds) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (PlaceId != 0) hash ^= PlaceId.GetHashCode();
          if (Script.Length != 0) hash ^= Script.GetHashCode();
          if (ExpirationInSeconds != 0) hash ^= ExpirationInSeconds.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (PlaceId != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(PlaceId);
          }
          if (Script.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Script);
          }
          if (ExpirationInSeconds != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ExpirationInSeconds);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (PlaceId != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(PlaceId);
          }
          if (Script.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Script);
          }
          if (ExpirationInSeconds != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(ExpirationInSeconds);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (PlaceId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlaceId);
          }
          if (Script.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Script);
          }
          if (ExpirationInSeconds != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ExpirationInSeconds);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Place other) {
          if (other == null) {
            return;
          }
          if (other.PlaceId != 0) {
            PlaceId = other.PlaceId;
          }
          if (other.Script.Length != 0) {
            Script = other.Script;
          }
          if (other.ExpirationInSeconds != 0) {
            ExpirationInSeconds = other.ExpirationInSeconds;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                PlaceId = input.ReadUInt32();
                break;
              }
              case 18: {
                Script = input.ReadString();
                break;
              }
              case 24: {
                ExpirationInSeconds = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                PlaceId = input.ReadUInt32();
                break;
              }
              case 18: {
                Script = input.ReadString();
                break;
              }
              case 24: {
                ExpirationInSeconds = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Thumbnail : pb::IMessage<Thumbnail>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Thumbnail> _parser = new pb::MessageParser<Thumbnail>(() => new Thumbnail());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Thumbnail> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Kiseki.Arbiter.Proto.Signal.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Thumbnail() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Thumbnail(Thumbnail other) : this() {
          type_ = other.type_;
          assetId_ = other.assetId_;
          accessKey_ = other.accessKey_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Thumbnail Clone() {
          return new Thumbnail(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Kiseki.Arbiter.Proto.AssetType type_ = global::Kiseki.Arbiter.Proto.AssetType.Clothing;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Kiseki.Arbiter.Proto.AssetType Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "assetId" field.</summary>
        public const int AssetIdFieldNumber = 2;
        private uint assetId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint AssetId {
          get { return assetId_; }
          set {
            assetId_ = value;
          }
        }

        /// <summary>Field number for the "accessKey" field.</summary>
        public const int AccessKeyFieldNumber = 3;
        private string accessKey_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string AccessKey {
          get { return accessKey_; }
          set {
            accessKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Thumbnail);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Thumbnail other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Type != other.Type) return false;
          if (AssetId != other.AssetId) return false;
          if (AccessKey != other.AccessKey) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Type != global::Kiseki.Arbiter.Proto.AssetType.Clothing) hash ^= Type.GetHashCode();
          if (AssetId != 0) hash ^= AssetId.GetHashCode();
          if (AccessKey.Length != 0) hash ^= AccessKey.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Type != global::Kiseki.Arbiter.Proto.AssetType.Clothing) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Type);
          }
          if (AssetId != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(AssetId);
          }
          if (AccessKey.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(AccessKey);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Type != global::Kiseki.Arbiter.Proto.AssetType.Clothing) {
            output.WriteRawTag(8);
            output.WriteEnum((int) Type);
          }
          if (AssetId != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(AssetId);
          }
          if (AccessKey.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(AccessKey);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Type != global::Kiseki.Arbiter.Proto.AssetType.Clothing) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (AssetId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AssetId);
          }
          if (AccessKey.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessKey);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Thumbnail other) {
          if (other == null) {
            return;
          }
          if (other.Type != global::Kiseki.Arbiter.Proto.AssetType.Clothing) {
            Type = other.Type;
          }
          if (other.AssetId != 0) {
            AssetId = other.AssetId;
          }
          if (other.AccessKey.Length != 0) {
            AccessKey = other.AccessKey;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Type = (global::Kiseki.Arbiter.Proto.AssetType) input.ReadEnum();
                break;
              }
              case 16: {
                AssetId = input.ReadUInt32();
                break;
              }
              case 26: {
                AccessKey = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Type = (global::Kiseki.Arbiter.Proto.AssetType) input.ReadEnum();
                break;
              }
              case 16: {
                AssetId = input.ReadUInt32();
                break;
              }
              case 26: {
                AccessKey = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kiseki.Arbiter.Proto.KisekiReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      operation_ = other.operation_;
      success_ = other.success_;
      message_ = other.message_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 1;
    private global::Kiseki.Arbiter.Proto.Operation operation_ = global::Kiseki.Arbiter.Proto.Operation.OpenJob;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Kiseki.Arbiter.Proto.Operation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 2;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 4;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operation != other.Operation) return false;
      if (Success != other.Success) return false;
      if (Message != other.Message) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) hash ^= Operation.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operation);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operation);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Operation != global::Kiseki.Arbiter.Proto.Operation.OpenJob) {
        Operation = other.Operation;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Operation = (global::Kiseki.Arbiter.Proto.Operation) input.ReadEnum();
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
          case 34: {
            Data = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Operation = (global::Kiseki.Arbiter.Proto.Operation) input.ReadEnum();
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
          case 34: {
            Data = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
