//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tadah.Tampa.Server
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tadah.rocks/", ConfigurationName="Tadah.Tampa.Server.Soap")]
    public interface Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.Status GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.Status> GetStatusAsync();
        
        // CODEGEN: Parameter 'OpenJobResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/OpenJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.OpenJobResponse OpenJob(Tadah.Tampa.Server.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/OpenJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.OpenJobResponse> OpenJobAsync(Tadah.Tampa.Server.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/OpenJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.LuaValue[] OpenJobEx(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/OpenJobEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> OpenJobExAsync(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/RenewLease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double RenewLease(string jobID, double expirationInSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/RenewLease", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds);
        
        // CODEGEN: Parameter 'ExecuteResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.ExecuteResponse Execute(Tadah.Tampa.Server.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.ExecuteResponse> ExecuteAsync(Tadah.Tampa.Server.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/ExecuteEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.LuaValue[] ExecuteEx(string jobID, Tadah.Tampa.Server.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/ExecuteEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> ExecuteExAsync(string jobID, Tadah.Tampa.Server.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/CloseJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CloseJob(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/CloseJob", ReplyAction="*")]
        System.Threading.Tasks.Task CloseJobAsync(string jobID);
        
        // CODEGEN: Parameter 'BatchJobResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/BatchJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.BatchJobResponse BatchJob(Tadah.Tampa.Server.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/BatchJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.BatchJobResponse> BatchJobAsync(Tadah.Tampa.Server.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/BatchJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.LuaValue[] BatchJobEx(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/BatchJobEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> BatchJobExAsync(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetExpiration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double GetExpiration(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetExpiration", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID);
        
        // CODEGEN: Parameter 'GetAllJobsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.GetAllJobsResponse GetAllJobs(Tadah.Tampa.Server.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetAllJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.GetAllJobsResponse> GetAllJobsAsync(Tadah.Tampa.Server.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetAllJobsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.Job[] GetAllJobsEx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/GetAllJobsEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.Job[]> GetAllJobsExAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/CloseExpiredJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CloseExpiredJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/CloseExpiredJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CloseExpiredJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/CloseAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CloseAllJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/CloseAllJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CloseAllJobsAsync();
        
        // CODEGEN: Parameter 'DiagResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/Diag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.DiagResponse Diag(Tadah.Tampa.Server.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/Diag", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.DiagResponse> DiagAsync(Tadah.Tampa.Server.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/DiagEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Tampa.Server.LuaValue[] DiagEx(int type, string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tadah.rocks/DiagEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> DiagExAsync(int type, string jobID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tadah.rocks/")]
    public partial class Status
    {
        
        private string versionField;
        
        private int environmentCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int environmentCount
        {
            get
            {
                return this.environmentCountField;
            }
            set
            {
                this.environmentCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tadah.rocks/")]
    public partial class LuaValue
    {
        
        private LuaType typeField;
        
        private string valueField;
        
        private LuaValue[] tableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LuaType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tadah.rocks/")]
    public enum LuaType
    {
        
        /// <remarks/>
        LUA_TNIL,
        
        /// <remarks/>
        LUA_TBOOLEAN,
        
        /// <remarks/>
        LUA_TNUMBER,
        
        /// <remarks/>
        LUA_TSTRING,
        
        /// <remarks/>
        LUA_TTABLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tadah.rocks/")]
    public partial class ScriptExecution
    {
        
        private string nameField;
        
        private string scriptField;
        
        private LuaValue[] argumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string script
        {
            get
            {
                return this.scriptField;
            }
            set
            {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tadah.rocks/")]
    public partial class Job
    {
        
        private string idField;
        
        private double expirationInSecondsField;
        
        private int categoryField;
        
        private double coresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double expirationInSeconds
        {
            get
            {
                return this.expirationInSecondsField;
            }
            set
            {
                this.expirationInSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cores
        {
            get
            {
                return this.coresField;
            }
            set
            {
                this.coresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJob", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class OpenJobRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        public Tadah.Tampa.Server.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=1)]
        public Tadah.Tampa.Server.ScriptExecution script;
        
        public OpenJobRequest()
        {
        }
        
        public OpenJobRequest(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJobResponse", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class OpenJobResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OpenJobResult")]
        public Tadah.Tampa.Server.LuaValue[] OpenJobResult;
        
        public OpenJobResponse()
        {
        }
        
        public OpenJobResponse(Tadah.Tampa.Server.LuaValue[] OpenJobResult)
        {
            this.OpenJobResult = OpenJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Execute", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        public string jobID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=1)]
        public Tadah.Tampa.Server.ScriptExecution script;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(string jobID, Tadah.Tampa.Server.ScriptExecution script)
        {
            this.jobID = jobID;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExecuteResult", IsNullable=true)]
        public Tadah.Tampa.Server.LuaValue[] ExecuteResult;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(Tadah.Tampa.Server.LuaValue[] ExecuteResult)
        {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJob", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class BatchJobRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        public Tadah.Tampa.Server.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=1)]
        public Tadah.Tampa.Server.ScriptExecution script;
        
        public BatchJobRequest()
        {
        }
        
        public BatchJobRequest(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJobResponse", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class BatchJobResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BatchJobResult", IsNullable=true)]
        public Tadah.Tampa.Server.LuaValue[] BatchJobResult;
        
        public BatchJobResponse()
        {
        }
        
        public BatchJobResponse(Tadah.Tampa.Server.LuaValue[] BatchJobResult)
        {
            this.BatchJobResult = BatchJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobs", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class GetAllJobsRequest
    {
        
        public GetAllJobsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobsResponse", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class GetAllJobsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetAllJobsResult", IsNullable=true)]
        public Tadah.Tampa.Server.Job[] GetAllJobsResult;
        
        public GetAllJobsResponse()
        {
        }
        
        public GetAllJobsResponse(Tadah.Tampa.Server.Job[] GetAllJobsResult)
        {
            this.GetAllJobsResult = GetAllJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Diag", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class DiagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=1)]
        public string jobID;
        
        public DiagRequest()
        {
        }
        
        public DiagRequest(int type, string jobID)
        {
            this.type = type;
            this.jobID = jobID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DiagResponse", WrapperNamespace="http://tadah.rocks/", IsWrapped=true)]
    public partial class DiagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tadah.rocks/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DiagResult", IsNullable=true)]
        public Tadah.Tampa.Server.LuaValue[] DiagResult;
        
        public DiagResponse()
        {
        }
        
        public DiagResponse(Tadah.Tampa.Server.LuaValue[] DiagResult)
        {
            this.DiagResult = DiagResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface Channel : Tadah.Tampa.Server.Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Client : System.ServiceModel.ClientBase<Tadah.Tampa.Server.Soap>, Tadah.Tampa.Server.Soap
    {
        
        public Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public Client(string endpointConfigurationName, string remoteAddress) : base(endpointConfigurationName, remoteAddress)
        {
        }

        public string HelloWorld()
        {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync()
        {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetVersion()
        {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public Tadah.Tampa.Server.Status GetStatus()
        {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.Status> GetStatusAsync()
        {
            return base.Channel.GetStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Tampa.Server.OpenJobResponse Tadah.Tampa.Server.Soap.OpenJob(Tadah.Tampa.Server.OpenJobRequest request)
        {
            return base.Channel.OpenJob(request);
        }
        
        public Tadah.Tampa.Server.LuaValue[] OpenJob(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            Tadah.Tampa.Server.OpenJobRequest inValue = new Tadah.Tampa.Server.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            Tadah.Tampa.Server.OpenJobResponse retVal = ((Tadah.Tampa.Server.Soap)(this)).OpenJob(inValue);
            return retVal.OpenJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.OpenJobResponse> Tadah.Tampa.Server.Soap.OpenJobAsync(Tadah.Tampa.Server.OpenJobRequest request)
        {
            return base.Channel.OpenJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.OpenJobResponse> OpenJobAsync(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            Tadah.Tampa.Server.OpenJobRequest inValue = new Tadah.Tampa.Server.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((Tadah.Tampa.Server.Soap)(this)).OpenJobAsync(inValue);
        }
        
        public Tadah.Tampa.Server.LuaValue[] OpenJobEx(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            return base.Channel.OpenJobEx(job, script);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> OpenJobExAsync(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            return base.Channel.OpenJobExAsync(job, script);
        }
        
        public double RenewLease(string jobID, double expirationInSeconds)
        {
            return base.Channel.RenewLease(jobID, expirationInSeconds);
        }
        
        public System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds)
        {
            return base.Channel.RenewLeaseAsync(jobID, expirationInSeconds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Tampa.Server.ExecuteResponse Tadah.Tampa.Server.Soap.Execute(Tadah.Tampa.Server.ExecuteRequest request)
        {
            return base.Channel.Execute(request);
        }
        
        public Tadah.Tampa.Server.LuaValue[] Execute(string jobID, Tadah.Tampa.Server.ScriptExecution script)
        {
            Tadah.Tampa.Server.ExecuteRequest inValue = new Tadah.Tampa.Server.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            Tadah.Tampa.Server.ExecuteResponse retVal = ((Tadah.Tampa.Server.Soap)(this)).Execute(inValue);
            return retVal.ExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.ExecuteResponse> Tadah.Tampa.Server.Soap.ExecuteAsync(Tadah.Tampa.Server.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.ExecuteResponse> ExecuteAsync(string jobID, Tadah.Tampa.Server.ScriptExecution script)
        {
            Tadah.Tampa.Server.ExecuteRequest inValue = new Tadah.Tampa.Server.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            return ((Tadah.Tampa.Server.Soap)(this)).ExecuteAsync(inValue);
        }
        
        public Tadah.Tampa.Server.LuaValue[] ExecuteEx(string jobID, Tadah.Tampa.Server.ScriptExecution script)
        {
            return base.Channel.ExecuteEx(jobID, script);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> ExecuteExAsync(string jobID, Tadah.Tampa.Server.ScriptExecution script)
        {
            return base.Channel.ExecuteExAsync(jobID, script);
        }
        
        public void CloseJob(string jobID)
        {
            base.Channel.CloseJob(jobID);
        }
        
        public System.Threading.Tasks.Task CloseJobAsync(string jobID)
        {
            return base.Channel.CloseJobAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Tampa.Server.BatchJobResponse Tadah.Tampa.Server.Soap.BatchJob(Tadah.Tampa.Server.BatchJobRequest request)
        {
            return base.Channel.BatchJob(request);
        }
        
        public Tadah.Tampa.Server.LuaValue[] BatchJob(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            Tadah.Tampa.Server.BatchJobRequest inValue = new Tadah.Tampa.Server.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            Tadah.Tampa.Server.BatchJobResponse retVal = ((Tadah.Tampa.Server.Soap)(this)).BatchJob(inValue);
            return retVal.BatchJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.BatchJobResponse> Tadah.Tampa.Server.Soap.BatchJobAsync(Tadah.Tampa.Server.BatchJobRequest request)
        {
            return base.Channel.BatchJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.BatchJobResponse> BatchJobAsync(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            Tadah.Tampa.Server.BatchJobRequest inValue = new Tadah.Tampa.Server.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((Tadah.Tampa.Server.Soap)(this)).BatchJobAsync(inValue);
        }
        
        public Tadah.Tampa.Server.LuaValue[] BatchJobEx(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            return base.Channel.BatchJobEx(job, script);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> BatchJobExAsync(Tadah.Tampa.Server.Job job, Tadah.Tampa.Server.ScriptExecution script)
        {
            return base.Channel.BatchJobExAsync(job, script);
        }
        
        public double GetExpiration(string jobID)
        {
            return base.Channel.GetExpiration(jobID);
        }
        
        public System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID)
        {
            return base.Channel.GetExpirationAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Tampa.Server.GetAllJobsResponse Tadah.Tampa.Server.Soap.GetAllJobs(Tadah.Tampa.Server.GetAllJobsRequest request)
        {
            return base.Channel.GetAllJobs(request);
        }
        
        public Tadah.Tampa.Server.Job[] GetAllJobs()
        {
            Tadah.Tampa.Server.GetAllJobsRequest inValue = new Tadah.Tampa.Server.GetAllJobsRequest();
            Tadah.Tampa.Server.GetAllJobsResponse retVal = ((Tadah.Tampa.Server.Soap)(this)).GetAllJobs(inValue);
            return retVal.GetAllJobsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.GetAllJobsResponse> Tadah.Tampa.Server.Soap.GetAllJobsAsync(Tadah.Tampa.Server.GetAllJobsRequest request)
        {
            return base.Channel.GetAllJobsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.GetAllJobsResponse> GetAllJobsAsync()
        {
            Tadah.Tampa.Server.GetAllJobsRequest inValue = new Tadah.Tampa.Server.GetAllJobsRequest();
            return ((Tadah.Tampa.Server.Soap)(this)).GetAllJobsAsync(inValue);
        }
        
        public Tadah.Tampa.Server.Job[] GetAllJobsEx()
        {
            return base.Channel.GetAllJobsEx();
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.Job[]> GetAllJobsExAsync()
        {
            return base.Channel.GetAllJobsExAsync();
        }
        
        public int CloseExpiredJobs()
        {
            return base.Channel.CloseExpiredJobs();
        }
        
        public System.Threading.Tasks.Task<int> CloseExpiredJobsAsync()
        {
            return base.Channel.CloseExpiredJobsAsync();
        }
        
        public int CloseAllJobs()
        {
            return base.Channel.CloseAllJobs();
        }
        
        public System.Threading.Tasks.Task<int> CloseAllJobsAsync()
        {
            return base.Channel.CloseAllJobsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Tampa.Server.DiagResponse Tadah.Tampa.Server.Soap.Diag(Tadah.Tampa.Server.DiagRequest request)
        {
            return base.Channel.Diag(request);
        }
        
        public Tadah.Tampa.Server.LuaValue[] Diag(int type, string jobID)
        {
            Tadah.Tampa.Server.DiagRequest inValue = new Tadah.Tampa.Server.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            Tadah.Tampa.Server.DiagResponse retVal = ((Tadah.Tampa.Server.Soap)(this)).Diag(inValue);
            return retVal.DiagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Tampa.Server.DiagResponse> Tadah.Tampa.Server.Soap.DiagAsync(Tadah.Tampa.Server.DiagRequest request)
        {
            return base.Channel.DiagAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.DiagResponse> DiagAsync(int type, string jobID)
        {
            Tadah.Tampa.Server.DiagRequest inValue = new Tadah.Tampa.Server.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            return ((Tadah.Tampa.Server.Soap)(this)).DiagAsync(inValue);
        }
        
        public Tadah.Tampa.Server.LuaValue[] DiagEx(int type, string jobID)
        {
            return base.Channel.DiagEx(type, jobID);
        }
        
        public System.Threading.Tasks.Task<Tadah.Tampa.Server.LuaValue[]> DiagExAsync(int type, string jobID)
        {
            return base.Channel.DiagExAsync(type, jobID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
