//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tadah.Arbiter.RccServiceSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://roblox.com/", ConfigurationName="RccServiceSoap.RCCServiceSoap")]
    public interface RCCServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.Status GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.Status> GetStatusAsync();
        
        // CODEGEN: Parameter 'OpenJobResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.OpenJobResponse OpenJob(Tadah.Arbiter.RccServiceSoap.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.OpenJobResponse> OpenJobAsync(Tadah.Arbiter.RccServiceSoap.OpenJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.LuaValue[] OpenJobEx(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/OpenJobEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> OpenJobExAsync(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/RenewLease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double RenewLease(string jobID, double expirationInSeconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/RenewLease", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds);
        
        // CODEGEN: Parameter 'ExecuteResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.ExecuteResponse Execute(Tadah.Arbiter.RccServiceSoap.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.ExecuteResponse> ExecuteAsync(Tadah.Arbiter.RccServiceSoap.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/ExecuteEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.LuaValue[] ExecuteEx(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/ExecuteEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> ExecuteExAsync(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CloseJob(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseJob", ReplyAction="*")]
        System.Threading.Tasks.Task CloseJobAsync(string jobID);
        
        // CODEGEN: Parameter 'BatchJobResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.BatchJobResponse BatchJob(Tadah.Arbiter.RccServiceSoap.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.BatchJobResponse> BatchJobAsync(Tadah.Arbiter.RccServiceSoap.BatchJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJobEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.LuaValue[] BatchJobEx(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/BatchJobEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> BatchJobExAsync(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetExpiration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double GetExpiration(string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetExpiration", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID);
        
        // CODEGEN: Parameter 'GetAllJobsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.GetAllJobsResponse GetAllJobs(Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.GetAllJobsResponse> GetAllJobsAsync(Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.Job[] GetAllJobsEx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/GetAllJobsEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.Job[]> GetAllJobsExAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseExpiredJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CloseExpiredJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseExpiredJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CloseExpiredJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseAllJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CloseAllJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/CloseAllJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CloseAllJobsAsync();
        
        // CODEGEN: Parameter 'DiagResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Diag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.DiagResponse Diag(Tadah.Arbiter.RccServiceSoap.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/Diag", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.DiagResponse> DiagAsync(Tadah.Arbiter.RccServiceSoap.DiagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/DiagEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tadah.Arbiter.RccServiceSoap.LuaValue[] DiagEx(int type, string jobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://roblox.com/DiagEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> DiagExAsync(int type, string jobID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private int environmentCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int environmentCount {
            get {
                return this.environmentCountField;
            }
            set {
                this.environmentCountField = value;
                this.RaisePropertyChanged("environmentCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class LuaValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LuaType typeField;
        
        private string valueField;
        
        private LuaValue[] tableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LuaType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
                this.RaisePropertyChanged("table");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public enum LuaType {
        
        /// <remarks/>
        LUA_TNIL,
        
        /// <remarks/>
        LUA_TBOOLEAN,
        
        /// <remarks/>
        LUA_TNUMBER,
        
        /// <remarks/>
        LUA_TSTRING,
        
        /// <remarks/>
        LUA_TTABLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class ScriptExecution : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string scriptField;
        
        private LuaValue[] argumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
                this.RaisePropertyChanged("script");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LuaValue[] arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
                this.RaisePropertyChanged("arguments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://roblox.com/")]
    public partial class Job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private double expirationInSecondsField;
        
        private int categoryField;
        
        private double coresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double expirationInSeconds {
            get {
                return this.expirationInSecondsField;
            }
            set {
                this.expirationInSecondsField = value;
                this.RaisePropertyChanged("expirationInSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double cores {
            get {
                return this.coresField;
            }
            set {
                this.coresField = value;
                this.RaisePropertyChanged("cores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJob", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class OpenJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public Tadah.Arbiter.RccServiceSoap.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public Tadah.Arbiter.RccServiceSoap.ScriptExecution script;
        
        public OpenJobRequest() {
        }
        
        public OpenJobRequest(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OpenJobResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class OpenJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("OpenJobResult")]
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] OpenJobResult;
        
        public OpenJobResponse() {
        }
        
        public OpenJobResponse(Tadah.Arbiter.RccServiceSoap.LuaValue[] OpenJobResult) {
            this.OpenJobResult = OpenJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Execute", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public string jobID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public Tadah.Arbiter.RccServiceSoap.ScriptExecution script;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            this.jobID = jobID;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ExecuteResult", IsNullable=true)]
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] ExecuteResult;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Tadah.Arbiter.RccServiceSoap.LuaValue[] ExecuteResult) {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJob", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class BatchJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public Tadah.Arbiter.RccServiceSoap.Job job;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public Tadah.Arbiter.RccServiceSoap.ScriptExecution script;
        
        public BatchJobRequest() {
        }
        
        public BatchJobRequest(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            this.job = job;
            this.script = script;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchJobResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class BatchJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BatchJobResult", IsNullable=true)]
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] BatchJobResult;
        
        public BatchJobResponse() {
        }
        
        public BatchJobResponse(Tadah.Arbiter.RccServiceSoap.LuaValue[] BatchJobResult) {
            this.BatchJobResult = BatchJobResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobs", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class GetAllJobsRequest {
        
        public GetAllJobsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllJobsResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class GetAllJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("GetAllJobsResult", IsNullable=true)]
        public Tadah.Arbiter.RccServiceSoap.Job[] GetAllJobsResult;
        
        public GetAllJobsResponse() {
        }
        
        public GetAllJobsResponse(Tadah.Arbiter.RccServiceSoap.Job[] GetAllJobsResult) {
            this.GetAllJobsResult = GetAllJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Diag", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class DiagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=1)]
        public string jobID;
        
        public DiagRequest() {
        }
        
        public DiagRequest(int type, string jobID) {
            this.type = type;
            this.jobID = jobID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DiagResponse", WrapperNamespace="http://roblox.com/", IsWrapped=true)]
    public partial class DiagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://roblox.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DiagResult", IsNullable=true)]
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] DiagResult;
        
        public DiagResponse() {
        }
        
        public DiagResponse(Tadah.Arbiter.RccServiceSoap.LuaValue[] DiagResult) {
            this.DiagResult = DiagResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RCCServiceSoapChannel : Tadah.Arbiter.RccServiceSoap.RCCServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RCCServiceSoapClient : System.ServiceModel.ClientBase<Tadah.Arbiter.RccServiceSoap.RCCServiceSoap>, Tadah.Arbiter.RccServiceSoap.RCCServiceSoap {
        
        public RCCServiceSoapClient() {
        }
        
        public RCCServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RCCServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RCCServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RCCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
        
        public Tadah.Arbiter.RccServiceSoap.Status GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.Status> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Arbiter.RccServiceSoap.OpenJobResponse Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.OpenJob(Tadah.Arbiter.RccServiceSoap.OpenJobRequest request) {
            return base.Channel.OpenJob(request);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] OpenJob(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            Tadah.Arbiter.RccServiceSoap.OpenJobRequest inValue = new Tadah.Arbiter.RccServiceSoap.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            Tadah.Arbiter.RccServiceSoap.OpenJobResponse retVal = ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).OpenJob(inValue);
            return retVal.OpenJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.OpenJobResponse> Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.OpenJobAsync(Tadah.Arbiter.RccServiceSoap.OpenJobRequest request) {
            return base.Channel.OpenJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.OpenJobResponse> OpenJobAsync(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            Tadah.Arbiter.RccServiceSoap.OpenJobRequest inValue = new Tadah.Arbiter.RccServiceSoap.OpenJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).OpenJobAsync(inValue);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] OpenJobEx(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            return base.Channel.OpenJobEx(job, script);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> OpenJobExAsync(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            return base.Channel.OpenJobExAsync(job, script);
        }
        
        public double RenewLease(string jobID, double expirationInSeconds) {
            return base.Channel.RenewLease(jobID, expirationInSeconds);
        }
        
        public System.Threading.Tasks.Task<double> RenewLeaseAsync(string jobID, double expirationInSeconds) {
            return base.Channel.RenewLeaseAsync(jobID, expirationInSeconds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Arbiter.RccServiceSoap.ExecuteResponse Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.Execute(Tadah.Arbiter.RccServiceSoap.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] Execute(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            Tadah.Arbiter.RccServiceSoap.ExecuteRequest inValue = new Tadah.Arbiter.RccServiceSoap.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            Tadah.Arbiter.RccServiceSoap.ExecuteResponse retVal = ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).Execute(inValue);
            return retVal.ExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.ExecuteResponse> Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.ExecuteAsync(Tadah.Arbiter.RccServiceSoap.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.ExecuteResponse> ExecuteAsync(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            Tadah.Arbiter.RccServiceSoap.ExecuteRequest inValue = new Tadah.Arbiter.RccServiceSoap.ExecuteRequest();
            inValue.jobID = jobID;
            inValue.script = script;
            return ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).ExecuteAsync(inValue);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] ExecuteEx(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            return base.Channel.ExecuteEx(jobID, script);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> ExecuteExAsync(string jobID, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            return base.Channel.ExecuteExAsync(jobID, script);
        }
        
        public void CloseJob(string jobID) {
            base.Channel.CloseJob(jobID);
        }
        
        public System.Threading.Tasks.Task CloseJobAsync(string jobID) {
            return base.Channel.CloseJobAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Arbiter.RccServiceSoap.BatchJobResponse Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.BatchJob(Tadah.Arbiter.RccServiceSoap.BatchJobRequest request) {
            return base.Channel.BatchJob(request);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] BatchJob(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            Tadah.Arbiter.RccServiceSoap.BatchJobRequest inValue = new Tadah.Arbiter.RccServiceSoap.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            Tadah.Arbiter.RccServiceSoap.BatchJobResponse retVal = ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).BatchJob(inValue);
            return retVal.BatchJobResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.BatchJobResponse> Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.BatchJobAsync(Tadah.Arbiter.RccServiceSoap.BatchJobRequest request) {
            return base.Channel.BatchJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.BatchJobResponse> BatchJobAsync(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            Tadah.Arbiter.RccServiceSoap.BatchJobRequest inValue = new Tadah.Arbiter.RccServiceSoap.BatchJobRequest();
            inValue.job = job;
            inValue.script = script;
            return ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).BatchJobAsync(inValue);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] BatchJobEx(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            return base.Channel.BatchJobEx(job, script);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> BatchJobExAsync(Tadah.Arbiter.RccServiceSoap.Job job, Tadah.Arbiter.RccServiceSoap.ScriptExecution script) {
            return base.Channel.BatchJobExAsync(job, script);
        }
        
        public double GetExpiration(string jobID) {
            return base.Channel.GetExpiration(jobID);
        }
        
        public System.Threading.Tasks.Task<double> GetExpirationAsync(string jobID) {
            return base.Channel.GetExpirationAsync(jobID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Arbiter.RccServiceSoap.GetAllJobsResponse Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.GetAllJobs(Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest request) {
            return base.Channel.GetAllJobs(request);
        }
        
        public Tadah.Arbiter.RccServiceSoap.Job[] GetAllJobs() {
            Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest inValue = new Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest();
            Tadah.Arbiter.RccServiceSoap.GetAllJobsResponse retVal = ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).GetAllJobs(inValue);
            return retVal.GetAllJobsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.GetAllJobsResponse> Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.GetAllJobsAsync(Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest request) {
            return base.Channel.GetAllJobsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.GetAllJobsResponse> GetAllJobsAsync() {
            Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest inValue = new Tadah.Arbiter.RccServiceSoap.GetAllJobsRequest();
            return ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).GetAllJobsAsync(inValue);
        }
        
        public Tadah.Arbiter.RccServiceSoap.Job[] GetAllJobsEx() {
            return base.Channel.GetAllJobsEx();
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.Job[]> GetAllJobsExAsync() {
            return base.Channel.GetAllJobsExAsync();
        }
        
        public int CloseExpiredJobs() {
            return base.Channel.CloseExpiredJobs();
        }
        
        public System.Threading.Tasks.Task<int> CloseExpiredJobsAsync() {
            return base.Channel.CloseExpiredJobsAsync();
        }
        
        public int CloseAllJobs() {
            return base.Channel.CloseAllJobs();
        }
        
        public System.Threading.Tasks.Task<int> CloseAllJobsAsync() {
            return base.Channel.CloseAllJobsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tadah.Arbiter.RccServiceSoap.DiagResponse Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.Diag(Tadah.Arbiter.RccServiceSoap.DiagRequest request) {
            return base.Channel.Diag(request);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] Diag(int type, string jobID) {
            Tadah.Arbiter.RccServiceSoap.DiagRequest inValue = new Tadah.Arbiter.RccServiceSoap.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            Tadah.Arbiter.RccServiceSoap.DiagResponse retVal = ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).Diag(inValue);
            return retVal.DiagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.DiagResponse> Tadah.Arbiter.RccServiceSoap.RCCServiceSoap.DiagAsync(Tadah.Arbiter.RccServiceSoap.DiagRequest request) {
            return base.Channel.DiagAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.DiagResponse> DiagAsync(int type, string jobID) {
            Tadah.Arbiter.RccServiceSoap.DiagRequest inValue = new Tadah.Arbiter.RccServiceSoap.DiagRequest();
            inValue.type = type;
            inValue.jobID = jobID;
            return ((Tadah.Arbiter.RccServiceSoap.RCCServiceSoap)(this)).DiagAsync(inValue);
        }
        
        public Tadah.Arbiter.RccServiceSoap.LuaValue[] DiagEx(int type, string jobID) {
            return base.Channel.DiagEx(type, jobID);
        }
        
        public System.Threading.Tasks.Task<Tadah.Arbiter.RccServiceSoap.LuaValue[]> DiagExAsync(int type, string jobID) {
            return base.Channel.DiagExAsync(type, jobID);
        }
    }
}
