name: build

on: [push]

jobs:
  win-x86:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Checkout Code
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      
    - name: Build
      run: dotnet publish -r win-x86 -c release -o publish
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: win-x86
        path: publish
  
  win-x64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Checkout Code
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      
    - name: Build
      run: dotnet publish -r win-x64 -c release -o publish
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: win-x64
        path: publish
  
  linux-x64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Checkout Code
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      
    - name: Build
      run: dotnet publish -r linux-x64 -c release -o publish
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: publish
