name: Build
 
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore Tadah.Arbiter.sln
      
    - name: Build app for release
      run: msbuild Tadah.Arbiter.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Tadah.Arbiter
        path: bin\Release